env: 'local' # local, dev, prod
storage_path: './storage/storage.db'
http_server:
    address: 'localhost:8082'
    timeout: 4s # Время на чтение запроса и отправку ответа
    idle_timeout: 60s # Время жизни соединения с клиентом
postgres_connect:
    user: 'postgres'
    password: 'admin'
    dbname: 'tamagochi'
    sslmode: 'disable'
